### PR TITLE
fix: override generated endpoint class to correct type

### LINKED ISSUE #618: Type definition for `Endpoint` missing properties
### Describe what should be investigated or refactored

We consume our types from `@kubernetes/client-node`, however the [type](https://github.com/kubernetes-client/javascript/blob/adf37cc570787236981435256d5f3bab313785df/src/gen/models/V1Endpoint.ts#L21) for Endpoint is incorrect.

We need to ensure it has an apiVersion, kind, and metadata field with an array of subnets.

### PR DESCRIPTION
**Pull request by cmwylie19**
## Description

The generated `Endpoint` from the upstream library where our types are consumed is incorrect. It has only a subset of fields making it difficult to assert on the shape of the object in Pepr. This PR adds the `apiVersion`, `metadata`, `kind`, and corrects the `subnet` field to be an array like in the real endpoint schema.

```plaintext
KIND:       Endpoints
VERSION:    v1

DESCRIPTION:
    Endpoints is a collection of endpoints that implement the actual service.
    Example:
    
    	 Name: "mysvc",
    	 Subsets: [
    	   {
    	     Addresses: [{"ip": "10.10.1.1"}, {"ip": "10.10.2.2"}],
    	     Ports: [{"name": "a", "port": 8675}, {"name": "b", "port": 309}]
    	   },
    	   {
    	     Addresses: [{"ip": "10.10.3.3"}],
    	     Ports: [{"name": "a", "port": 93}, {"name": "b", "port": 76}]
    	   },
    	]
    
FIELDS:
  apiVersion	<string>
    APIVersion defines the versioned schema of this representation of an object.
    Servers should convert recognized schemas to the latest internal value, and
    may reject unrecognized values. More info:
    https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

  kind	<string>
    Kind is a string value representing the REST resource this object
    represents. Servers may infer this from the endpoint the client submits
    requests to. Cannot be updated. In CamelCase. More info:
    https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

  metadata	<ObjectMeta>
    Standard object's metadata. More info:
    https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata

  subsets	<[]EndpointSubset>
    The set of all endpoints is the union of all subsets. Addresses are placed
    into subsets according to the IPs they share. A single address with multiple
    ports, some of which are ready and some of which are not (because they come
    from different containers) will result in the address being displayed in
    different subsets for the different ports. No address will appear in both
    Addresses and NotReadyAddresses in the same subset. Sets of addresses and
    ports that comprise a service.
```

## Related Issue

Fixes #618 

Relates to #

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://docs.pepr.dev/main/contribute/#submitting-a-pull-request) followed

### CODE REVIEW

File: src/upstream.ts [hunk 1]
```diff
@@ -49,7 +51,37 @@ export {
   V1TokenReview as TokenReview,
   V1ValidatingWebhookConfiguration as ValidatingWebhookConfiguration,
   V1VolumeAttachment as VolumeAttachment,
-  V1Endpoint as Endpoint,
+  // V1Endpoint as Endpoint, - keep this so we do not forget incase it is corrected
 } from "@kubernetes/client-node";
 
 export { GenericKind } from "./types";
+
+export class Endpoint {
```
Comment (samayer12) [inline src/upstream.ts:59]: Can we test this under `kinds.test.ts`? It looks we have some sort of basic test for all the other kinds we support

Comment (cmwylie19) [reply src/upstream.ts:59]: good idea

Comment (samayer12) [reply src/upstream.ts:59]: ty!

**Review by samayer12 — APPROVED** [review]
